name: My Test Workflow
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths-ignore:
  #     - ".github/workflows/*"
  # pull_request:
  #   types: [opened, edited, reopened]

env:
  RECORD_KEY: ${{ secrets.RECORD_KEY }}

jobs:
  testing1:
    runs-on: ubuntu-latest
    container:
    image: node16.18.0-chrome107.0.5304.68-ff106.0.1-edge
    steps:
      - name: Add env vars
        run: export RECORD_KEY=${{env.RECORD_KEY}}
      - name: Get the project code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install --force
      - name: Run tests
        run: npm run cypress:e2e
      - name: Generate reports
        run: npm run generate:report
        if: failure() || success()
      - name: Save test report
        uses: actions/upload-artifact@v3
        with:
          path: mochawesome-report
          name: Test Report
        if: failure() || success()
      - name: Get test report
        uses: actions/download-artifact@v3
        with:
          name: Test Report
        if: failure() || success()
  testing2:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.6.1-chrome-116.0.5845.187-1-ff-117.0-edge-116.0.1938.76-1
    steps:
      - name: Add env vars
        run: export RECORD_KEY=${{env.RECORD_KEY}}
      - name: Get the project code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install --force
      - name: Run tests
        run: npm run cypress:e2e
      - name: Generate reports
        run: npm run generate:report
        if: failure() || success()
      - name: Save test report
        uses: actions/upload-artifact@v3
        with:
          path: mochawesome-report
          name: Test Report
        if: failure() || success()
      - name: Get test report
        uses: actions/download-artifact@v3
        with:
          name: Test Report
        if: failure() || success()
